/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cache/gltf/vehicle/rx7/BRAKE_OFF.glb --output src/components/vehicle/rx7/BrakeOff.jsx --draco 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BRAKE_OFF.glb')
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  )
}

useGLTF.preload('/BRAKE_OFF.glb')
