/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cache/gltf/vehicle/rx7/MAIN.glb --output src/components/vehicle/rx7/Main.jsx --draco 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cache/gltf/vehicle/rx7/MAIN.glb')
  console.log('Main GLTF data:', { nodes, materials })
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  )
}

useGLTF.preload('/cache/gltf/vehicle/rx7/MAIN.glb')
